### ISSUE TITLE
Doesn't work with python 2.7

### ISSUE THREAD

**Issue by mohsinkhn** [nerox8664/pytorch2keras#60]
**Describe the bug**
The code doesn't work with python 2.7. `converter.py` in line 210 imports `SimpleNamespace` from `types` which was added only in python3.3, so it throws error for me. Any suggestions to quickly fix this will be appreciated a lot. Thanks! 

**Code**
     resnet = models.resnet50(pretrained=False)
     modules = list(resnet.children())[:-1]
     model = nn.Sequential(*modules)

     state_dict = load_checkpoint("resnet50_weights.pth")
     model.load_state_dict(state_dict)
     print("loading weights to resnet successful")
     torch.save({'state_dict': state_dict}, "im2recipe_resent_weigts.pth")

     input_np = np.random.uniform(0, 1, (1, 3, 224, 224))
     input_var = Variable(torch.FloatTensor(input_np))
     k_model = pytorch_to_keras(model, input_var, (3, 224, 224), verbose=True)

**Error**
Traceback (most recent call last):
  File "get_resnet_weights.py", line 34, in <module>
    k_model = pytorch_to_keras(model, input_var, (3, 224, 224), verbose=True)
  File "/home/mohsin/visio/scripts/im2recipe/py27/local/lib/python2.7/site-packages/pytorch2keras/converter.py", line 210, in pytorch_to_keras
    from types import SimpleNamespace
ImportError: cannot import name SimpleNamespace

**Environment**
 - Ubuntu 16.04
 - Python 2.7.12

**Comment by nerox8664** [comment]
hello @mohsinkhn.
I fixed this issue. Can you fetch the latest (git master) version and try again?

**Comment by mohsinkhn** [comment]
Thanks! It works on master.
